version: '2'
services:
    avgreport-app:
        image: avgreport
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://avgreport-mysql:3306/avgreport?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8187:8187
    avgreport-mysql:
        extends:
            file: mysql.yml
            service: avgreport-mysql
